<<<<<<< HEAD
86400000
=======
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
  port: 8080
  servlet:
    context-path: /strongprettyhomes/api
spring:
  datasource:
    password:
    url: jdbc:postgresql://localhost:5432/strongprettyhomes
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

#    show-sql: true
  servlet:
    multipart:
      max-request-size: 2MB
      max-file-size: 2MB
    show-sql: true


backendapi:
  app:
    jwtSecret: carRentalSecretKey
    jwtExpirationMs: 86400000
>>>>>>> main
